
#include <fstream>
#include <iostream>
#include <string>

void build_header(std::string file) {
    auto fin = std::ifstream(file);

    if (!fin.is_open()) {
        std::cerr << "No such file " << file << "\n";
        std::exit(1);
    }

    std::string prefix = file.substr(0, file.find_last_of("."));
    std::string out_name = prefix + ".h";
    auto fout = std::ofstream(out_name);

    if (!fout.is_open()) {
        std::cerr << "Cannot open " << out_name << " for writing\n";
        std::exit(1);
    }

    fout << "// Generated by build_header\n\n";
    fout << "static const char* " << prefix << " = \"";

    size_t word_count = 0;
    size_t len = 0;
    std::string line;
    while (std::getline(fin, line)) {
        fout << line << "\\n";
        len += line.size() + 1;
        word_count++;
    }
    fout << "\";\n";
    fout << "static const size_t " << prefix << "_len = " << len << ";\n";
    //std::cout << "Wrote " << word_count << " words to " << out_name << "\n";
}

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cout << "Usage: " << argv[0] << " [filename]\n";
        std::exit(1);
    }
    build_header(argv[1]);
}
